name: custom_appbar_plus
description: A customizable Flutter AppBar widget with flexible styling options like title, actions, elevation, and colors.


version: 1.0.1
homepage: https://github.com/sawriyasoni09/custom_appbar
repository: https://github.com/sawriyasoni09/custom_appbar
issue_tracker: https://github.com/sawriyasoni09/custom_appbar/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


topics:
  - appbar
  - custom-widget
  - material-design